### ISSUE TITLE
Commands Page is Completely Broken

### ISSUE THREAD

**Issue by RemingtonHolder** [zeroclutch/gamebot-website#1]
Commands page is completely bugged out... Screenshot below:
![image](https://user-images.githubusercontent.com/45955060/118422722-c49bf380-b691-11eb-94b6-5bf6f0b20333.png)

**Comment by RemingtonHolder** [comment]
This must be a network configuration issue. Because whenever me(the client) tried to fetch the commands it shoots a 403 error. I downloaded this repo and tested it on my machine and the commands page worked no problem.

**Comment by zeroclutch** [comment]
Thanks for the report, this issue has been resolved.
